% Programmer: socexp, WZJ, 20210724 
% gdt: game dynamics theory
% Input: the subfold of the abed experiment csv files
% Output: statics analysis result 
%         save('manifold20210724try.mat', ...
%           'rr_abed_csv', ... % rr_abed_csv{:,:,3}
%         'rr_dos_x_t', ...
%         'rr_E_mean_std', ...
%         'rr_E_angularmom', ...
%         'rr_eigen_vector', ...
%         'rr_d_eigen_value', ...
%         'rr_T_eigencycle', ...
%         'rr_rest_no', ...
%         'rr_solu_list', .. %cell2mat(rr_solu_list(:,:,3))
%         'rr_coef_coefint3col', ...
%         'rr_resid_residint3col', ...
%         'rr_R2_F_p_evar', ...
%         'rr_M5x5');
%% Test command 
% gdt_integrate_onlyMean('F:\tmpdata\result_exp202107\','F:\tmpdata\result_ana202107\InvMani0725_onlyMean.mat','F:\tmpdata\result_ana202107\InvMani0725_dosXt.mat')

function r=gdt_integrate_onlyMean(file_abedcsv_path,file_save_mat,file_dos_xt_mat)
            %file_abedcsv_path='F:\tmpdata\result_exp202107\';
         [rr_M5x5, fileNames]=get_5x5_from_abedExp(file_abedcsv_path); 
    
    for fj = 1:size(fileNames,1);
        % abed experiment data 
            abed_csv = fileNames{fj}; 
                abedfilesname = strcat(file_abedcsv_path,abed_csv)
            dos_x_t = get_dos_x_t_from_abeddata(abedfilesname);
         [E_angularmom,mn,am_eigencycleDim_t, E_mean, E_std] = ...
                from_N_colExp_out_am(dos_x_t);
                [E_mean; E_std] 
% % %        % theoretical result
% % %          [eigen_vector, d_eigen_value, T_eigencycle, n0, solu_list] = ...
% % %                  get_eigensystem_from_5x5(rr_M5x5(:,:,fj)); 
% % %        % statics analysis
% % %          [coef_coefint3col,resid_residint3col,R2_F_p_evar] = ... 
% % %                  multi_reg_Eam_Tec(E_angularmom,T_eigencycle);   
% % %                   coef_coefint3col'  
% % %                   R2_F_p_evar
       % data organized
%           if size(d_eigen_value) == 5 
            rr_abed_csv(:,:,fj) = {abed_csv}; % rr_abed_csv{:,:,3}
            rr_dos_x_t(:,:,fj) = dos_x_t;
            rr_E_mean_std(:,:,fj) = [E_mean' E_std'];
            rr_E_angularmom(:,:,fj) = E_angularmom;  
% % %             rr_eigen_vector(:,:,fj) =  eigen_vector;
% % %             rr_d_eigen_value(:,:,fj) = d_eigen_value'; 
% % %             rr_T_eigencycle(:,:,fj) =  T_eigencycle;
% % %             rr_rest_no(:,:,fj) =  n0;
% % %             rr_solu_list(:,:,fj) = {solu_list}; %cell2mat(rr_solu_list(:,:,3))
% % %             rr_coef_coefint3col(:,:,fj) = coef_coefint3col;
% % %             rr_resid_residint3col(:,:,fj) = resid_residint3col;
% % %             rr_R2_F_p_evar(:,:,fj) = R2_F_p_evar;
%           end
    end 
    
    % save results
        %file_save_mat = 'manifold20210724try.mat'
        save(file_save_mat, 'rr_abed_csv', ...
                            'rr_E_mean_std', ...
                            'rr_E_angularmom', ... %%%
                            'rr_M5x5'); 
         save(file_dos_xt_mat, 'rr_dos_x_t', 'rr_M5x5')
end 


% % %                             'rr_eigen_vector', ...
% % %                             'rr_d_eigen_value', ...
% % %                             'rr_T_eigencycle', ...
% % %                             'rr_rest_no', ...
% % %                             'rr_solu_list', ...
% % %                             'rr_coef_coefint3col', ...
% % %                             'rr_resid_residint3col', ...
% % %                             'rr_R2_F_p_evar', ...